# HTTP Server Configuration

[server]
host = "127.0.0.1"
port = 9090
read_timeout_seconds = 30
write_timeout_seconds = 30

[threading]
worker_threads = 4
max_concurrent_connections = 100

[connection]
max_idle_connections = 20
idle_timeout_seconds = 30
keep_alive_timeout_seconds = 60
buffer_size = 8192

[static_files]
enabled = true
directory = "static"
index_file = "index.html"
directory_listing = true

[authentication]
enabled = true
user_user = "secret"
user_admin = "password123"
protected_path_1 = "/admin"

[logging]
enabled = true
level = "info"
log_requests = true
log_responses = false
